language: node_js
node_js:
  - '6.0.0'
  - '6.1.0'
  - '6.2.0'
  - '6.2.1'
deploy:
  provider: npm
  email: ivo.putzer@gmail.com
  api_key: NPM_API_KEY
  on:
    repo: ivoputzer/m.noop
    branch: master
